In [1]:
import os
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
# import data of hiv/aids diagnostic
raw_data = os.path.join('HIV_AIDS_Diagnoses_by_Neighborhood__Sex__and_Race_Ethnicity.csv')

In [3]:
#read the data 
read_data = pd.read_csv(raw_data)
read_data.head()

,YEAR,Neighborhood,SEX,RACE_ETHNICITY,TOTAL_NUMBER_OF_HIV_DIAGNOSES,HIV_DIAGNOSES_PER_100K_POPULATION,TOTAL_NUMBER_OF_CONCURRENT_HIV_AIDS_DIAGNOSES,PROPORTION_OF_CONCURRENT_HIV_AIDS_DIAGNOSES_AMONG_ALL_HIV_DIAGNOSES,TOTAL_NUMBER_OF_AIDS_DIAGNOSES,AIDS_DIAGNOSES_PER_100K_POPULATION
0,2010,Greenpoint,Male,Black,6,330.4,0,0,5,275.3
1,2011,Stapleton - St. George,Female,Native American,0,0,0,0,0,0
2,2010,Southeast Queens,Male,All,23,25.4,5,21.7,14,15.4
3,2012,Upper Westside,Female,Unknown,0,0,0,0,0,0
4,2013,Willowbrook,Male,Unknown,0,0,0,0,0,0

In [4]:
read_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2928 entries, 0 to 2927
Data columns (total 10 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   YEAR                                                                 2928 non-null   int64
 1   Neighborhood                                                         2928 non-null   object
 2   SEX                                                                  2928 non-null   object
 3   RACE_ETHNICITY                                                       2928 non-null   object
 4   TOTAL_NUMBER_OF_HIV_DIAGNOSES                                        2928 non-null   object
 5   HIV_DIAGNOSES_PER_100K_POPULATION                                    2860 non-null   object
 6   TOTAL_NUMBER_OF_CONCURRENT_HIV_AIDS_DIAGNOSES                        2928 non-null   object
 7   PROPORTION_OF_CONCURRENT_HIV_AIDS_DIAGNOSES_AMONG_ALL_HIV_DIAGNOSES  2860 non-null   object
 8   TOTAL_NUMBER_OF_AIDS_DIAGNOSES                                       2928 non-null   object
 9   AIDS_DIAGNOSES_PER_100K_POPULATION                                   2860 non-null   object
dtypes: int64(1), object(9)
memory usage: 228.9+ KB

In [5]:
read_data.shape

(2928, 10)

In [6]:
# unique values in the columns
read_data.RACE_ETHNICITY.unique()

array(['Black', 'Native American', 'All', 'Unknown', 'Multiracial',
       'Asian/Pacific Islander', 'White', 'Hispanic'], dtype=object)

In [7]:
# clean the race ethnicity to convert all to unknown race, 
read_data['RACE_ETHNICITY'] = read_data ['RACE_ETHNICITY'].replace(['All'],['Unknown'])

In [8]:
# clean sex column, convert all to unknown
read_data['SEX'] = read_data['SEX'].replace(['All'],['Unknown'])

In [9]:
# cleand neighborhood data replacing all with unknown
read_data['Neighborhood'] = read_data['Neighborhood'].replace(['All'],['Unknown'])

In [10]:
#count null value
read_data.isnull().sum()

YEAR                                                                    0
Neighborhood                                                            0
SEX                                                                     0
RACE_ETHNICITY                                                          0
TOTAL_NUMBER_OF_HIV_DIAGNOSES                                           0
HIV_DIAGNOSES_PER_100K_POPULATION                                      68
TOTAL_NUMBER_OF_CONCURRENT_HIV_AIDS_DIAGNOSES                           0
PROPORTION_OF_CONCURRENT_HIV_AIDS_DIAGNOSES_AMONG_ALL_HIV_DIAGNOSES    68
TOTAL_NUMBER_OF_AIDS_DIAGNOSES                                          0
AIDS_DIAGNOSES_PER_100K_POPULATION                                     68
dtype: int64

In [11]:
# remove null value
data = read_data.dropna().sort_values(by='YEAR')

In [12]:
data

,YEAR,Neighborhood,SEX,RACE_ETHNICITY,TOTAL_NUMBER_OF_HIV_DIAGNOSES,HIV_DIAGNOSES_PER_100K_POPULATION,TOTAL_NUMBER_OF_CONCURRENT_HIV_AIDS_DIAGNOSES,PROPORTION_OF_CONCURRENT_HIV_AIDS_DIAGNOSES_AMONG_ALL_HIV_DIAGNOSES,TOTAL_NUMBER_OF_AIDS_DIAGNOSES,AIDS_DIAGNOSES_PER_100K_POPULATION
0,2010,Greenpoint,Male,Black,6,330.4,0,0,5,275.3
539,2010,Crotona - Tremont,Male,Black,35,122.8,5,14.3,31,108.8
2091,2010,Port Richmond,Unknown,Unknown,11,15.6,3,27.3,7,9.9
541,2010,East Harlem,Female,Native American,0,0,0,0,0,0
2090,2010,East Harlem,Male,White,15,224.5,4,26.7,11,164.6
...,...,...,...,...,...,...,...,...,...,...
590,2013,Hunts Point - Mott Haven,Male,Unknown,0,0,0,0,0,0
588,2013,Canarsie - Flatlands,Unknown,Unknown,53,26.7,18,34,33,16.6
2007,2013,Central Harlem - Morningside Heights,Male,Hispanic,31,162.1,7,22.6,14,73.2
2013,2013,Washington Heights - Inwood,Male,Hispanic,52,61.7,4,7.7,16,19
2048,2013,Hunts Point - Mott Haven,Female,Asian/Pacific Islander,0,0,0,0,0,0

In [18]:
data.to_csv('clean_data.csv')